# Generated by Django 4.1.2 on 2023-01-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0011_address_region"),
        ("app_announcement", "0003_alter_announcement_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements",
                to="app_users.staff",
            ),
        ),
    ]
