# Generated by Django 4.0.5 on 2022-08-12 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_campus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="campus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_campus.campus",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="classification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app_campus.venueclassification",
            ),
        ),
    ]
