# Generated by Django 4.0.5 on 2022-08-16 13:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_campus', '0002_alter_venue_campus_alter_venue_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={},
        ),
        migrations.AlterField(
            model_name='venue',
            name='campus',
            field=models.ForeignKey(help_text='The Campus that the Venue is located within.', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_campus.campus'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='classification',
            field=models.ForeignKey(help_text='Type of the Venue.', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_campus.venueclassification'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='code',
            field=models.CharField(help_text='A short standardized code.', max_length=64, validators=[django.core.validators.RegexValidator(message="Username must match this: '[a-zA-Z0-9_]{8,32}'", regex='[a-zA-Z0-9_]{8,32}')]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.CharField(help_text='The location of the Venue in a certain Campus. For example, room and floor number.', max_length=64, validators=[django.core.validators.RegexValidator(message="Field must match this: '[a-zA-Z0-9_\\-\\(\\) ]'", regex='[a-zA-Z0-9_\\-\\(\\) ]')]),
        ),
        migrations.AlterField(
            model_name='venueclassification',
            name='description',
            field=models.TextField(default='...'),
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('code', 'campus')},
        ),
    ]
