# Generated by Django 4.1.2 on 2022-12-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_campus", "0003_alter_venue_options_alter_venue_campus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="campus",
            field=models.ForeignKey(
                help_text="The Campus that the Venue is located within.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venues",
                to="app_campus.campus",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="classification",
            field=models.ForeignKey(
                help_text="Type of the Venue.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="venues",
                to="app_campus.venueclassification",
            ),
        ),
    ]
