# Generated by Django 4.1.2 on 2023-05-11 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_campus", "0004_alter_venue_campus_alter_venue_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="code",
            field=models.CharField(
                help_text="A short standardized code.",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username/code must match this: '[a-zA-Z0-9_]{8,32}'",
                        regex="[a-zA-Z0-9_]{8,32}",
                    )
                ],
            ),
        ),
    ]
