# Generated by Django 4.1.2 on 2022-11-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_course", "0005_alter_course_color"),
        ("app_assignment", "0002_rename_instruction_submission_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_course.course",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CourseAssignment",
        ),
    ]
