# Generated by Django 4.1.2 on 2022-11-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_assignment", "0003_assignment_course_delete_courseassignment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="criteria",
            new_name="grading_criteria",
        ),
    ]
