# Generated by Django 4.1.2 on 2023-01-16 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app_assignment", "0004_rename_criteria_assignment_grading_criteria"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="attachment",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="submissionattachment",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attachment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="submissionattachment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submissionattachment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
