# Generated by Django 4.0.5 on 2022-08-16 13:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='config',
            field=models.JSONField(help_text='Event configuration saved in the json format.'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator(message="Field must match this: '[a-zA-Z0-9_\\-\\(\\) ]'", regex='[a-zA-Z0-9_\\-\\(\\) ]')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='...'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='A short standardized code.', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message="Username must match this: '[a-zA-Z0-9_]{8,32}'", regex='[a-zA-Z0-9_]{8,32}')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='...'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(help_text='The course ending date.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(help_text='The course starting date.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='classification',
            field=models.ForeignKey(help_text='The type of the event.', on_delete=django.db.models.deletion.PROTECT, to='app_course.eventclassification'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='The date that the event falls onto.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_from',
            field=models.TimeField(help_text='Starting time of the event.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_to',
            field=models.TimeField(help_text='Ending time of the event.'),
        ),
        migrations.AlterField(
            model_name='eventclassification',
            name='description',
            field=models.TextField(default='...'),
        ),
    ]
