# Generated by Django 4.0.5 on 2022-08-12 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Field must match this: '[a-zA-Z0-9_\\-\\(\\) ]'",
                                regex="[a-zA-Z0-9_\\-\\(\\) ]",
                            )
                        ],
                    ),
                ),
                ("config", models.JSONField()),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=256,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Field must match this: '[a-zA-Z0-9_\\-\\(\\) ]'",
                        regex="[a-zA-Z0-9_\\-\\(\\) ]",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username must match this: '[a-zA-Z0-9_]{8,32}'",
                        regex="[a-zA-Z0-9_]{8,32}",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                max_length=256,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Field must match this: '[a-zA-Z0-9_\\-\\(\\) ]'",
                        regex="[a-zA-Z0-9_\\-\\(\\) ]",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="eventclassification",
            name="name",
            field=models.CharField(
                max_length=256,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Field must only contain basic Latin characters and spaces.",
                        regex="[a-zA-Z ]",
                    )
                ],
            ),
        ),
    ]
