# Generated by Django 4.0.5 on 2022-08-12 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(message="Field must match this: '[a-zA-Z0-9_\\-\\(\\) ]'", regex='[a-zA-Z0-9_\\-\\(\\) ]')])),
                ('config', models.JSONField()),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
