# Generated by Django 4.0.5 on 2022-08-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_course", "0002_alter_calendar_config_alter_calendar_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_course.course",
            ),
            preserve_default=False,
        ),
    ]
