# Generated by Django 4.0.5 on 2022-09-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_course', '0003_event_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default='#FA7070', max_length=50),
        ),
    ]
