# Generated by Django 4.0.5 on 2022-09-23 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_course', '0004_course_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(default='#FA7070', max_length=50, validators=[django.core.validators.RegexValidator(message="Color code must match this: '#[a-zA-Z0-9]{6}'", regex='^#[a-zA-Z0-9]{6}$')]),
        ),
    ]
