# Generated by Django 4.1.2 on 2022-11-03 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_course", "0006_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                default="T.Su Event",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Field must match this: '[a-zA-Z0-9_\\-\\(\\) ]'",
                        regex="[a-zA-Z0-9_\\-\\(\\) ]",
                    )
                ],
            ),
        ),
    ]
