# Generated by Django 4.1.2 on 2022-12-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_campus", "0004_alter_venue_campus_alter_venue_classification"),
        ("app_course", "0007_alter_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="app_course.category",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="classification",
            field=models.ForeignKey(
                help_text="The type of the event.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="app_course.eventclassification",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="app_course.course",
            ),
        ),
        migrations.AlterField(
            model_name="eventvenue",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_venues",
                to="app_course.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventvenue",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_venues",
                to="app_campus.venue",
            ),
        ),
    ]
