# Generated by Django 4.1.2 on 2023-01-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_course",
            "0008_alter_course_category_alter_event_classification_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[("on_campus", "On Campus"), ("online", "Online")],
                default="online",
                max_length=10,
            ),
        ),
    ]
