# Generated by Django 4.1.2 on 2023-02-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_course", "0009_course_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="classification",
            field=models.CharField(
                choices=[
                    ("lecture", "lecture"),
                    ("holiday", "holiday"),
                    ("exam", "exam"),
                    ("other", "other"),
                ],
                max_length=128,
            ),
        ),
        migrations.DeleteModel(
            name="EventClassification",
        ),
    ]
