# Generated by Django 4.1.2 on 2023-05-11 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_course", "0010_alter_event_classification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="channel_id",
            field=models.CharField(default="niga", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="ms_id",
            field=models.CharField(default="niga", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                help_text="A short standardized code.",
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username/code must match this: '[a-zA-Z0-9_]{8,32}'",
                        regex="[a-zA-Z0-9_]{8,32}",
                    )
                ],
            ),
        ),
    ]
