# Generated by Django 4.0.5 on 2022-08-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='the name of the record', max_length=256, unique=True)),
                ('status', models.CharField(help_text="status will be in the list of ['processing','approved','declined']", max_length=256)),
                ('bank_type', models.CharField(help_text="the type of the bank used to made the transaction. it will be in the list of ['KBZ', 'AYA', 'CB', 'KBZ_Pay']", max_length=256)),
                ('amount', models.IntegerField(help_text='the monetary value of the transaction.')),
                ('approved_on', models.DateTimeField(help_text='the date of approval made by an admin.', null=True)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
