# Generated by Django 4.0.5 on 2022-07-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_finance", "0002_record_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="amount",
            field=models.IntegerField(
                default=341, help_text="the monetary value of the transaction."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="approved_on",
            field=models.DateTimeField(
                help_text="the date of approval made by an admin.", null=True
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="bank_type",
            field=models.CharField(
                default="default",
                help_text="the type of the bank used to made the transaction. it will be in the list of ['KBZ', 'AYA', 'CB', 'KBZ_Pay']",
                max_length=256,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="record",
            name="name",
            field=models.CharField(
                help_text="the name of the record", max_length=256, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="status",
            field=models.CharField(
                help_text="status will be in the list of ['processing','approved','declined']",
                max_length=256,
            ),
        ),
    ]
