# Generated by Django 4.0.5 on 2022-08-09 11:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={},
        ),
        migrations.AddField(
            model_name="staff",
            name="about",
            field=models.TextField(default="tell us something about yourself ..."),
        ),
        migrations.AddField(
            model_name="staff",
            name="avatar",
            field=models.ImageField(
                default="system/default_staff_profile.jpg", upload_to="staff/avatars"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="dob",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="formal_photo",
            field=models.ImageField(
                default="system/default_staff_formal_photo.jpg",
                upload_to="staff/formal_photos",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="gender",
            field=models.CharField(default="male", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="primary_phone_number",
            field=models.CharField(
                default="+25 3462363",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        message="phone number must match this: '^[\\d+ ]{6,20}$'",
                        regex="^[\\d+ ]{6,20}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="secondary_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="secondary_phone_number",
            field=models.CharField(
                max_length=256,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="phone number must match this: '^[\\d+ ]{6,20}$'",
                        regex="^[\\d+ ]{6,20}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="username",
            field=models.CharField(
                default="username",
                max_length=256,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="username must match this: '^[\\w\\d_]{8,32}$'",
                        regex="^[\\w\\d_]{8,32}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.CharField(
                        max_length=256,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="username must match this: '^[\\w\\d_]{8,32}$'",
                                regex="^[\\w\\d_]{8,32}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "about",
                    models.TextField(default="tell us something about yourself ..."),
                ),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=128)),
                ("secondary_email", models.EmailField(max_length=254, null=True)),
                (
                    "primary_phone_number",
                    models.CharField(
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="phone number must match this: '^[\\d+ ]{6,20}$'",
                                regex="^[\\d+ ]{6,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "secondary_phone_number",
                    models.CharField(
                        max_length=256,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="phone number must match this: '^[\\d+ ]{6,20}$'",
                                regex="^[\\d+ ]{6,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="system/default_staff_profile.jpg",
                        upload_to="staff/avatars",
                    ),
                ),
                (
                    "formal_photo",
                    models.ImageField(
                        default="system/default_student_formal_photo.jpg",
                        upload_to="student/formal_photos",
                    ),
                ),
                (
                    "guardian_type",
                    models.CharField(
                        choices=[
                            ("father", "father"),
                            ("mother", "mother"),
                            ("relative", "relative"),
                            ("other", "other"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.CharField(
                        max_length=256,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="username must match this: '^[\\w\\d_]{8,32}$'",
                                regex="^[\\w\\d_]{8,32}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "about",
                    models.TextField(default="tell us something about yourself ..."),
                ),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=128)),
                ("secondary_email", models.EmailField(max_length=254, null=True)),
                (
                    "primary_phone_number",
                    models.CharField(
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="phone number must match this: '^[\\d+ ]{6,20}$'",
                                regex="^[\\d+ ]{6,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "secondary_phone_number",
                    models.CharField(
                        max_length=256,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="phone number must match this: '^[\\d+ ]{6,20}$'",
                                regex="^[\\d+ ]{6,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="system/default_staff_profile.jpg",
                        upload_to="staff/avatars",
                    ),
                ),
                (
                    "career",
                    models.CharField(
                        choices=[("teacher", "teacher"), ("engineer", "engineer")],
                        max_length=128,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
