# Generated by Django 4.0.5 on 2022-08-17 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0002_alter_staffaddress_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guardian",
            name="name",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Field must only contain basic Latin characters and spaces.",
                        regex="[a-zA-Z ]",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="name",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Field must only contain basic Latin characters and spaces.",
                        regex="[a-zA-Z ]",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Field must only contain basic Latin characters and spaces.",
                        regex="[a-zA-Z ]",
                    )
                ],
            ),
        ),
    ]
