# Generated by Django 4.0.5 on 2022-08-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0003_address_bankaccount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guardian",
            name="avatar",
            field=models.ImageField(
                default="system/default_profile.jpg", upload_to="guardian/avatar"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="avatar",
            field=models.ImageField(
                default="system/default_profile.jpg", upload_to="staff/avatar"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="formal_photo",
            field=models.ImageField(
                default="system/default_formal.jpg", upload_to="staff/formal_photos"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="avatar",
            field=models.ImageField(
                default="system/default_profile.jpg", upload_to="student/avatar"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="formal_photo",
            field=models.ImageField(
                default="system/default_formal.jpg", upload_to="student/formal_photos"
            ),
        ),
    ]
