# Generated by Django 4.0.5 on 2022-08-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0004_alter_guardian_avatar_alter_staff_avatar_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guardian",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="staffaddress",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="staffbankaccount",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="studentaddress",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="studentbankaccount",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_type",
            field=models.CharField(
                choices=[("KBZ", "KBZ"), ("AYA", "AYA"), ("CB", "CB"), ("UAB", "UAB")],
                max_length=256,
            ),
        ),
    ]
