# Generated by Django 4.0.5 on 2022-08-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_guardian_name_alter_staff_name_and_more'),
        ('app_users', '0004_alter_phonenumber_unique_together_and_more'),
    ]

    operations = [
    ]
