# Generated by Django 4.0.5 on 2022-09-23 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_merge_20220822_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.address'),
        ),
    ]
