# Generated by Django 4.0.5 on 2022-09-26 13:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_alter_studentaddress_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffbankaccount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staffbankaccount',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='staffbankaccount',
            name='staff',
        ),
        migrations.AlterUniqueTogether(
            name='studentaddress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentaddress',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='studentbankaccount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentbankaccount',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='studentbankaccount',
            name='student',
        ),
        migrations.AddField(
            model_name='address',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.guardian'),
        ),
        migrations.AddField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='A flag for whether current Address is a primary one or not.'),
        ),
        migrations.AddField(
            model_name='address',
            name='save_name',
            field=models.CharField(default='my_address', help_text='The name to save the current Address as.', max_length=256, validators=[django.core.validators.RegexValidator(message="Field must match this: '[a-zA-Z0-9_\\-\\(\\) ]'", regex='[a-zA-Z0-9_\\-\\(\\) ]')]),
        ),
        migrations.AddField(
            model_name='address',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.staff'),
        ),
        migrations.AddField(
            model_name='address',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.student'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.guardian'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='A flag for whether current BankAccount is a primary one or not.'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='save_name',
            field=models.CharField(default='my_bankaccount', help_text='The name to save the current BankAccount as.', max_length=256, validators=[django.core.validators.RegexValidator(message="Field must match this: '[a-zA-Z0-9_\\-\\(\\) ]'", regex='[a-zA-Z0-9_\\-\\(\\) ]')]),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.staff'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('student', 'save_name'), ('guardian', 'save_name'), ('staff', 'save_name')},
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('student', 'save_name'), ('guardian', 'save_name'), ('staff', 'save_name')},
        ),
        migrations.DeleteModel(
            name='StaffAddress',
        ),
        migrations.DeleteModel(
            name='StaffBankAccount',
        ),
        migrations.DeleteModel(
            name='StudentAddress',
        ),
        migrations.DeleteModel(
            name='StudentBankAccount',
        ),
    ]
