# Generated by Django 4.1.2 on 2022-12-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0010_alter_address_account_alter_bankaccount_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="region",
            field=models.CharField(
                choices=[
                    ("Kachin", "Kachin"),
                    ("Kayah", "Kayah"),
                    ("Kayin", "Kayin"),
                    ("Chin", "Chin"),
                    ("Mon", "Mon"),
                    ("Rakhine", "Rakhine"),
                    ("Shan", "Shan"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
