# Generated by Django 4.1.2 on 2023-02-03 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0011_address_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phonenumber",
            name="account",
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="staff",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_numbers",
                to="app_users.staff",
            ),
        ),
    ]
