# Generated by Django 4.1.2 on 2023-02-03 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_users", "0012_remove_phonenumber_account_phonenumber_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phonenumber",
            name="staff",
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_numbers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
