# Generated by Django 4.1.2 on 2023-02-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0013_remove_phonenumber_staff_phonenumber_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="roles",
            field=models.JSONField(default=["assistant-teacher"]),
            preserve_default=False,
        ),
    ]
