# Generated by Django 4.1.2 on 2023-02-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0014_staff_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="roles",
            field=models.JSONField(default=["assistant-teacher"]),
        ),
    ]
