# Generated by Django 4.1.2 on 2023-05-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0016_alter_phonenumber_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="guardian_type",
            field=models.CharField(
                choices=[
                    ("father", "father"),
                    ("mother", "mother"),
                    ("relative", "relative"),
                    ("other", "other"),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
