# Generated by Django 4.1.2 on 2023-05-11 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0017_alter_student_guardian_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guardian",
            name="username",
            field=models.CharField(
                max_length=256,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username/code must match this: '[a-zA-Z0-9_]{8,32}'",
                        regex="[a-zA-Z0-9_]{8,32}",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="username",
            field=models.CharField(
                max_length=256,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username/code must match this: '[a-zA-Z0-9_]{8,32}'",
                        regex="[a-zA-Z0-9_]{8,32}",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(
                max_length=256,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username/code must match this: '[a-zA-Z0-9_]{8,32}'",
                        regex="[a-zA-Z0-9_]{8,32}",
                    )
                ],
            ),
        ),
    ]
