# Generated by Django 4.1.2 on 2022-12-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0002_tempemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                error_messages={
                    "required": {
                        "default": "This field is required.",
                        "user": "Hey Studpid, How do you create an account without email?",
                    }
                },
                help_text="The user's email address ending in the organisation's domain.",
                max_length=254,
                unique=True,
            ),
        ),
    ]
