# Generated by Django 4.0.5 on 2022-08-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0003_account_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="account",
            name="user_permissions",
        ),
    ]
