# Generated by Django 4.1.2 on 2022-12-13 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0005_alter_account_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempemail",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temp_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
