# Generated by Django 4.1.2 on 2023-05-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0007_alter_account_email_alter_account_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="ms_id",
            field=models.CharField(default="niga", max_length=128),
            preserve_default=False,
        ),
    ]
