# Generated by Django 4.0.5 on 2022-08-11 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_course", "0001_initial"),
        ("app_users", "0006_alter_address_country_alter_guardian_career"),
        ("app_management", "0002_department_job_permission_role_staffsession_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StaffSession",
            new_name="StaffEvent",
        ),
        migrations.RemoveField(
            model_name="staffdepartment",
            name="is_under",
        ),
        migrations.AlterField(
            model_name="job",
            name="credit_per_session",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username must match this: '[a-zA-Z0-9_]{8,32}'",
                        regex="[a-zA-Z0-9_]{8,32}",
                    )
                ],
            ),
        ),
    ]
