# Generated by Django 4.0.7 on 2022-10-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_management",
            "0002_alter_grouprole_options_alter_rolepermission_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="parent_id",
            new_name="parent",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="parent_id",
            new_name="parent",
        ),
    ]
