# Generated by Django 4.0.5 on 2022-08-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_management", "0003_rename_staffsession_staffevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffdepartment",
            name="is_under",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_management.staffdepartment",
            ),
        ),
    ]
