# Generated by Django 4.1.2 on 2023-01-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_management", "0006_alter_group_parent_alter_grouprole_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffdepartment",
            name="is_under",
            field=models.ForeignKey(
                help_text="The Staff that the current staff is under the authority of.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_staffs_departments",
                to="app_management.staffdepartment",
            ),
        ),
        migrations.AlterField(
            model_name="staffdepartment",
            name="job",
            field=models.ForeignKey(
                help_text="The job that the Staff does in this particular relation.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staffs_departments",
                to="app_management.job",
            ),
        ),
    ]
