# Generated by Django 4.1.2 on 2023-01-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_management", "0007_alter_staffdepartment_is_under_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
