# Generated by Django 4.1.2 on 2023-02-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_management", "0008_role_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="code",
            field=models.CharField(
                default="ok",
                help_text="Some 'system jobs' are hard-coded in the frontend and are referenced by this code.",
                max_length=256,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
