# Generated by Django 4.1.2 on 2023-03-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_management", "0009_job_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_deletable",
            field=models.BooleanField(
                default=True,
                help_text="Some jobs are used by the system and is non-deletable.",
            ),
        ),
    ]
