# Generated by Django 4.1.2 on 2023-05-11 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_management", "0010_job_is_deletable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username/code must match this: '[a-zA-Z0-9_]{8,32}'",
                        regex="[a-zA-Z0-9_]{8,32}",
                    )
                ],
            ),
        ),
    ]
